#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "filebrowser-quantum"
name = "FileBrowser Quantum"
description.en = "Web File Browser"
description.fr = "Navigateur de fichiers Web"

version = "2.0.4-beta~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Apache-2.0"
admindoc = "https://filebrowserquantum.com/en/docs/getting-started/linux/"
code = "https://github.com/gtsteffaniak/filebrowser"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "100M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "filebrowser"
    extract = false
    amd64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v2.0.4-beta/linux-amd64-filebrowser"
    amd64.sha256 = "5b8fc10e1b54529466e6153b42ff9861da9f19d0f3492f72fca921094e2a44df"
    arm64.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v2.0.4-beta/linux-arm64-filebrowser"
    arm64.sha256 = "3d630a0a61077ac560063b5188896936d7c957e299b63d43a038783e9f6c3f6c"
    armhf.url = "https://github.com/gtsteffaniak/filebrowser/releases/download/v2.0.4-beta/linux-armv7-filebrowser"
    armhf.sha256 = "7d94a2e620091383fc9fa11b45acc6e7aa2d6436b1859a2572e1d19a9ec99bd4"
    autoupdate.strategy = "latest_github_release"
    autoupdate.version_regex = "v(\\d+\\.\\d+\\.\\d+)-stable"
    autoupdate.asset.amd64 = "linux-amd64-filebrowser"
    autoupdate.asset.arm64 = "linux-arm64-filebrowser"
    autoupdate.asset.armhf = "linux-armv7-filebrowser"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
